### ISSUE TITLE
ICGC JupyterHub updates for ICGC Paris

### ISSUE THREAD

**Issue by andricDu** [overture-stack/Jupyter#40]
## Requirements:
- [x] https://github.com/overture-stack/Jupyter/issues/33 Remove DACO
- [x] https://github.com/overture-stack/Jupyter/issues/34 Rename Directory
- [x] https://github.com/overture-stack/Jupyter/issues/35 Dynamic Download Example Notebook
- [x] https://github.com/overture-stack/Jupyter/issues/38 Fix Titles inside Notebooks
- [x] https://github.com/overture-stack/Jupyter/issues/39 Better Notebook Names

## Wishes: 
- [ ] https://github.com/overture-stack/Jupyter/issues/36 Sequence Logo Plot
- [ ] https://github.com/overture-stack/Jupyter/issues/37 Pileup example
